### ISSUE TITLE
x509-exporter should not go in subdirectories

### ISSUE THREAD

**Issue by abuisine** [enix/x509-exporter#1]
I see two problems in that :
- while monitoring `/etc/kubernetes/pki` it handles `/etc/kubernetes/pki/expired` which is created by standard kubeadm installations
- x509-exporter test all files and tries to recognize a certificate, it might be dangerons to walk through hundreds of subdirectories

**Comment by npdgm** [comment]
This was fixed in 3059c609e13f2465366a086c768d6fa4b5306570 and released in v1.5.3
